### ISSUE TITLE
Navigation within the wizard

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#10]
**Describe bug**
User is able to navigate to later steps in the wizard within having completed earlier steps.

**Steps to reproduce the bug**
User is logged in and fills out the wizard to review section. 
User then logs out opens up the wizard in the logged out state.
The completed steps still showed and user was able to navigate throughout the wizard as a logged out user.

**Comment by ThomasKranitsas** [comment]
The correct behavior is:

- If data exists in cookies and the user is not logged in, when the user logs in, create the challenge by calling the API and clean-up the cookies.
- When the user visits the wizard while being logged in, the data should be fetched from the API and not the cookies.
- If the user logs out, clean the cookies. When the user visits the wizard again after logging out, we need to make sure the form is empty and they start from the beginning.

Note: You can assume that each user will only have one Draft self-service challenge.
