### ISSUE TITLE
Work Details: Summary - Next action is incorrect

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#100]
Work Details: Summary - Next action is incorrect
The next action says `NEXT ACTION - ACCEPT: DUE NOW` even though the work is still in submitted state

<img width="1297" alt="Screenshot 2022-01-28 at 12 01 43 PM" src="https://user-images.githubusercontent.com/58783823/151499023-d0e5729e-e875-472b-bd4c-a0eb439245c6.png">

**Comment by Oanh-and-only-Oanh** [comment]
removing "next-action" feature from MVP.
