### ISSUE TITLE
Review Page: Missing info

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#102]
The following information is missing in the review page and also in the work details page details tab
1. Basic info: `HOW MANY PAGES?`

<img width="932" alt="Screenshot 2022-01-28 at 12 43 40 PM" src="https://user-images.githubusercontent.com/58783823/151503773-a45bced9-b361-4687-9891-8e5885434e2e.png">

2. Branding : Inspiration fields `(Website Address (optional)` and `What Do You Like (optional)`
3. Branding  `How to Use Your Fonts (optional)` field
4. Branding `ALLOW STOCK PHOTOS?` field

<img width="856" alt="Screenshot 2022-01-28 at 12 51 36 PM" src="https://user-images.githubusercontent.com/58783823/151504446-1b74f3a9-5b02-42f2-a8d5-b369be60f5e6.png">

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , point 1 (Basic info: HOW MANY PAGES?) is still missing
<img width="1320" alt="Screenshot 2022-02-01 at 8 38 14 AM" src="https://user-images.githubusercontent.com/58783823/151907549-cea47c74-19b5-4e60-b5b0-e4251dab1798.png">

**Comment by SathyaJayabal** [comment]
not fixed.

**Comment by SathyaJayabal** [comment]
not fixed
https://github.com/topcoder-platform/micro-frontends-self-service-app/issues/102#issuecomment-1026436381
<img width="1440" alt="Screenshot 2022-02-02 at 9 55 04 PM" src="https://user-images.githubusercontent.com/58783823/152194681-02d585d7-b33f-440f-9371-a4f42951b747.png">

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-557

**Comment by Oanh-and-only-Oanh** [comment]
Add the "number of pages" to the review page.

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1315" alt="Screenshot 2022-02-03 at 9 38 49 AM" src="https://user-images.githubusercontent.com/58783823/152279739-10b0303f-a2c8-47a4-96b2-249090864229.png">
