### ISSUE TITLE
Some challenges are getting created without any details.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-self-service-app#103]
Description:

Some challenges are getting created without any details.

The challenges are missing the below information
1. The challenge name is created by default as NEW-SELF-SERVICE-PROJECT
2. The details of the challenge are missing.
3. Prize amount details.

Sample Work Ids: 693a3eb9-977a-4881-b91f-1c570854b04f, 4c2c87a7-01a0-4940-bcec-149bbb652076, 861f044f-56f6-40a3-b6e8-840ba02ce4a8

https://user-images.githubusercontent.com/55895538/151504898-9600692c-bc3d-40db-ac79-8244f967b6c0.mp4

**Comment by ThomasKranitsas** [comment]
@SathyaJayabal this is part of the fix that was recently deployed. Please check again

**Comment by sandhiyakavi** [comment]
Verified in Dev Env.

![image](https://user-images.githubusercontent.com/55895538/151910924-5ff97f3a-a580-4c30-9a7f-5d00bcea065e.png)
![image](https://user-images.githubusercontent.com/55895538/151911472-2d73949f-6ca4-4cce-83d3-99af614476f1.png)
![image](https://user-images.githubusercontent.com/55895538/151911493-ac436301-9af9-41ee-b8a2-8f3be16fa256.png)
