### ISSUE TITLE
The optional fields that are not entered are getting displayed in the Challenge details page.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-self-service-app#104]
Description:

The optional fields that are not entered in the Create Work wizard are getting displayed in the Challenge details page of Community app.

![image](https://user-images.githubusercontent.com/55895538/151505618-41ffee9c-b09d-48e8-996c-33d3cf3630e0.png)
![image](https://user-images.githubusercontent.com/55895538/151505656-6cc9d228-1020-42ad-9e3c-d4ee32e2a5a5.png)

**Comment by Oanh-and-only-Oanh** [comment]
@ThomasKranitsas, we need to clean up the challenge details inputs. Please refer to this challenge details page for desired formatting. https://platform.topcoder.com/earn/find/challenges/0ffd7a81-9a1b-4d01-9c53-30055a2dffc7

**Comment by sandhiyakavi** [comment]
Verified in dev Env.

![image](https://user-images.githubusercontent.com/55895538/151911963-cd180730-6a7f-45f8-9c71-8b12e9cdfa76.png)
![image](https://user-images.githubusercontent.com/55895538/151911981-b5ff767e-4aa5-4030-8d2b-0c5d706cd919.png)
