### ISSUE TITLE
Work Details Summary: Progress bar is incorrect

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#106]
When the challenge is approved, the progress bar should show that the work is in progress, but it shows that it is complete. Next action is also incorrect. At present there should bot be a next action while work is in progress
<img width="1259" alt="Screenshot 2022-01-28 at 2 00 38 PM" src="https://user-images.githubusercontent.com/58783823/151513277-50b08460-b7ee-4f29-99b6-ce12efcd8c3c.png">

Another example: progress bar shows as download is ready even though  approval phase is still open and downloads are not yet ready on the solutions tab
<img width="1251" alt="Screenshot 2022-01-28 at 4 23 26 PM" src="https://user-images.githubusercontent.com/58783823/151534906-830a5d5d-29e4-46aa-b1d7-d2abc6e3e761.png">
<img width="1228" alt="Screenshot 2022-01-28 at 4 24 59 PM" src="https://user-images.githubusercontent.com/58783823/151534964-a9918475-025a-41fb-8973-c4f9f8671f71.png">

**Comment by SathyaJayabal** [comment]
The Status label for the In-review and Solutions ready is incorrect (even though progress bar is correct)

<img width="1440" alt="In Review Status" src="https://user-images.githubusercontent.com/58783823/152109631-acbe952e-f5e9-46e3-b239-7d55f0c49c75.png">
<img width="1440" alt="Solutions Ready Status" src="https://user-images.githubusercontent.com/58783823/152109636-82c2c54a-aeb5-4e79-9809-90e95a2f5845.png">

**Comment by SathyaJayabal** [comment]
Note: Solutions ready phase does not display now for WRs, the image above was for a project tested yesterday. Today the phase moved from in review to done.

**Comment by ThomasKranitsas** [comment]
@SathyaJayabal can you please check again?

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-556

**Comment by SathyaJayabal** [comment]
Closing this as we are handling the issues here:
https://github.com/topcoder-platform/micro-frontends-self-service-app/issues/149
https://github.com/topcoder-platform/micro-frontends-self-service-app/issues/144
