### ISSUE TITLE
Email Notification for forum message : Link to open discussion is incomplete

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#108]
Email Notification for forum message : Link to open discussion is incomplete
Actual link: http://self-service/work-items/830d25b0-53c3-4536-9798-61a16fc03441/?tab=messaging
Expected link:  https://platform.topcoder-dev.com/self-service/work-items/830d25b0-53c3-4536-9798-61a16fc03441?tab=messaging
<img width="1369" alt="Screenshot 2022-01-28 at 2 23 11 PM" src="https://user-images.githubusercontent.com/58783823/151516650-b6ee498c-7a10-487b-a962-3845c406832f.png">

**Comment by ThomasKranitsas** [comment]
@jmgasper can we fix this or should we move it to the next release?

**Comment by jmgasper** [comment]
@ThomasKranitsas / @SathyaJayabal - This is just a config issue.  Its now fixed for future notifications sent.

**Comment by Oanh-and-only-Oanh** [comment]
@jmgasper @ThomasKranitsas @SathyaJayabal, can we get this tested and on dev ASAP?

**Comment by jmgasper** [comment]
@Oanh-and-only-Oanh - It's fixed.  Just a config issue.

**Comment by Oanh-and-only-Oanh** [comment]
@jmgasper, who is this dependent on?

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, can you please verify?

**Comment by SathyaJayabal** [comment]
verified on dev

https://user-images.githubusercontent.com/58783823/151738985-0ee49b89-7b69-4a15-9ad9-76cee1ac6cc4.mov
