### ISSUE TITLE
Feature Request : Messaging Tab: Option for New Discussion

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#109]
At present the customer can only reply to posts form members. There is no option to post a new discussion.
<img width="1440" alt="Screenshot 2022-01-28 at 2 31 45 PM" src="https://user-images.githubusercontent.com/58783823/151517788-107570f4-47a1-4a91-8ae8-faca556760b2.png">

**Comment by ThomasKranitsas** [comment]
@rmitchell-iii mentioned we should only have one thread where we have all questions
