### ISSUE TITLE
Clicking on a draft work should take the user to the last in progress step 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#112]
Clicking on a draft work should take the user to the last in progress step. At present the user is taken to the first step. The links previously completed steps are also not enabled in the progress indicator.

https://user-images.githubusercontent.com/58783823/151528924-76b491b2-5896-4f58-ab27-a513c430fdb8.mov

**Comment by ThomasKranitsas** [comment]
@SathyaJayabal this is part of the fix that was recently deployed. Please check again

**Comment by Oanh-and-only-Oanh** [comment]
We have a jira ticket for this already.

**Comment by SathyaJayabal** [comment]
reopening this as we need to verify this and close it here.

**Comment by sdgun** [comment]
This issue is not fixed, it still opens the step 1 sometimes as shown in the below video.

https://user-images.githubusercontent.com/4592712/151737767-62079c66-2d76-4338-a6df-8d65d7446db4.mp4

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-567

**Comment by marioskranitsas** [comment]
I think its working as expected

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.


https://user-images.githubusercontent.com/4592712/157593273-1b7e6273-8b0c-4bfe-956c-487fdb9bec1e.mp4

**Comment by sdgun** [comment]
Verified in production.


https://user-images.githubusercontent.com/4592712/158724036-e76e863e-8a72-4203-91ec-fc457eb42084.mp4
