### ISSUE TITLE
Change status labels to following in dashboard, item details, timeline, and emails:

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/micro-frontends-self-service-app#118]
Update the displayed statuses based on the design here https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=2143%3A4659

**Comment by SathyaJayabal** [comment]
1. We have an approved status that is not on the list. This is when the copilot approves the work, but has not launched the challenge yet. I think the status should still be submitted, until the challenge is launched. @Oanh-and-only-Oanh ?
<img width="1235" alt="Screenshot 2022-02-02 at 12 56 02 PM" src="https://user-images.githubusercontent.com/58783823/152111457-10ef877b-e0a1-45ae-9e1e-de0d8c729d34.png">

<img width="1440" alt="Screenshot 2022-02-02 at 12 55 47 PM" src="https://user-images.githubusercontent.com/58783823/152111437-dda006bd-7852-400e-a6c4-eee0f1a33c05.png">

2. What do you mean by `emails` in the title "Change status labels to following in dashboard, item details, timeline, and emails" ? There is no specific status label used in the notifictaion emails, We are verifying the email content based on the send grid templates. IS that enough?

**Comment by SathyaJayabal** [comment]
4. WR did not go through  `Solutions ready` Phase. It phase moved from `In Review` to "Done" directly and a random rating also appeared. User did not get an option to mark as done.

**Comment by SathyaJayabal** [comment]
Summary of testing status
<google-sheets-html-origin><style type="text/css"></style>

Status | Dashboard | Item Details | Timeline
-- | -- | -- | --
Draft | Pass | Pass | Pass
Submitted | Pass | Pass | Pass
Started | Pass | Pass | Pass
In Review | Fail (Still shown as Started) | Fail (Still shown as Started) | Pass
Solutions Ready | Fail (went directly to Done) | Fail (went directly to Done) | Failed (went directly to Done)
Done | Pass | Pass | Pass
Redirected | Pass | Pass | NA
Cancelled | Not tested | Not tested | Not tested
Approved | Fail (Invalid Status) | Fail (Invalid Status) | Fail (Invalid Status)

**Comment by ThomasKranitsas** [comment]
@SathyaJayabal can you please check again? I made some changes

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-553

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , regarding status labels
For `In Review` and `Solutions Ready` statuses, the status label in the timeline is good.
But the status label in the dashboard and item details is still `Started`

<img width="1240" alt="Screenshot 2022-02-03 at 11 52 52 AM" src="https://user-images.githubusercontent.com/58783823/152307023-4febc914-2396-4bf0-b7a8-af6ed0c0bbfe.png">
<img width="1440" alt="Screenshot 2022-02-03 at 12 55 40 PM" src="https://user-images.githubusercontent.com/58783823/152307038-7dcecd73-f573-4d74-be47-52c7821b937c.png">

**Comment by sdgun** [comment]
Both of the comments issues mentioned in [above comment](https://github.com/topcoder-platform/micro-frontends-self-service-app/issues/118#issuecomment-1028722412) still exist.


https://user-images.githubusercontent.com/4592712/152934316-26dc8513-267e-4a24-9391-91d635d33d6d.mp4


https://user-images.githubusercontent.com/4592712/152934321-fbe33187-df34-4fb7-a720-2e742e913fa7.mp4

**Comment by sandhiyakavi** [comment]
@ThomasKranitsas  Below issues still exist,
1. For In Review  status, the status label in the timeline is good but the status label in the dashboard and item details is still Started.
2. For Solution Ready status, the status label in the timeline is good but the status label in the dashboard and item details is changed to Done.
3. The Approved status is still shown as a status in the dashboard and item details while the timeline becomes grayed out like below.

<img width="960" alt="approved_state" src="https://user-images.githubusercontent.com/55895538/154238585-92c80163-ad49-47b3-8960-da034732649d.png">

@Oanh-and-only-Oanh currently the WR status changed to started once the challenge is launched but in timeline it changed to started only after registration phase is opened. So when the status should be started, after Launching the challenge or after the Registration phase is opened?

<img width="957" alt="started_still_submitted" src="https://user-images.githubusercontent.com/55895538/154241871-3e168c4d-91c1-488a-96ee-8697dac68d9c.png">

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas, Status updates are good except for the two issues:
1. Approved Status: can you clarify on this status. There is no approved status here
https://github.com/topcoder-platform/micro-frontends-self-service-app/issues/118#issue-1118244649
but in the JIRA (https://topcoder.atlassian.net/browse/PLAT-553) there is an approved status mentioned. If there is an approved status then we need to support it on the timeline too. And the approved state work is listed in the end below redirected items, It should be sorted accordingly after `submitted` and before `started`.
At present the timeline is greyed out when the WR in approved status.
<img width="1440" alt="Screenshot 2022-02-18 at 7 09 54 PM" src="https://user-images.githubusercontent.com/58783823/154693254-581fb489-6d35-46ce-9bc8-1b7d3a44af08.png">

2. When the submission phase ends and screening starts, the status is in-review as expected in the timeline. But it is still in "Started" state in the dashboard and item details
<img width="914" alt="Screenshot 2022-02-18 at 6 27 57 PM" src="https://user-images.githubusercontent.com/58783823/154692403-8c02eca6-fd42-4379-ab07-d77877e818e8.png">

Status summary
<img width="729" alt="Screenshot 2022-02-18 at 7 12 10 PM" src="https://user-images.githubusercontent.com/58783823/154693616-0ab8e0cb-5856-4d82-a52f-ea3978deb1af.png">

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , in review status issue is fixed

**Comment by ThomasKranitsas** [comment]
This is expected behaviour and it's caused by the delay of the OR/v5 sync in phases. We can't avoid that and we shouldn't add too much "hacky" code to mask such issues that are caused by system sync issues. Please ignore this issue

**Comment by sdgun** [comment]
Issue created for Approved status https://github.com/topcoder-platform/micro-frontends-self-service-app/issues/187
