### ISSUE TITLE
Terms and policies modals

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/micro-frontends-self-service-app#119]
### Payments step from the wizard
- Update the "Order Contract" link to not toggle the checkbox
- Clicking the "Order Contract" link should open a modal with the content of the Online Order Agreement (similar to the stock artwork policy)

### Branding step in the wizard
- Links in "stock artwork policy" page should open in a new tab

### Work Item Details page
- Clicking the links from the right sidebar should open a modal with the related term 

Docs have been shared via Slack

**Comment by sandhiyakavi** [comment]
@ThomasKranitsas For the "stock artwork policy" link in Branding step, it is opening as modal but in above description it is mentioned as open in a new tab. May I know what is expected?

https://user-images.githubusercontent.com/55895538/151785598-229cdc67-8689-41a5-92e4-5c7f65eff558.mp4

Others are working as expected.

Order contract link:
<img width="768" alt="online _order" src="https://user-images.githubusercontent.com/55895538/151785744-6b5ad68b-6d12-456f-8b04-ae818cb9832d.png">

Work Item Details page, right sidebar links.

![image](https://user-images.githubusercontent.com/55895538/151786011-422d33bf-260d-4ea2-808b-97a0fb97d69b.png)
<img width="771" alt="privacy policy" src="https://user-images.githubusercontent.com/55895538/151786034-32e8b7a5-2525-4042-9ac1-c95a2de9998d.png">
<img width="960" alt="terms" src="https://user-images.githubusercontent.com/55895538/151786047-a9f9e912-4486-4784-9ea0-e639c772eb34.png">

**Comment by ThomasKranitsas** [comment]
@sandhiyakavi the links inside the modals should open in a new tab. Not the modal itself.
I'm closing this issues which is part of the development and you can open new ones if you find any issues
