### ISSUE TITLE
When customer starts the wizard, previous cookies should be cleared

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#12]
When user clicks on "start work" on the homepage, they should start from a fresh wizard.

**Comment by ThomasKranitsas** [comment]
@Oanh-and-only-Oanh  What happens when a "Draft" work item already exists and the user is somehow on the dashboard page? Do we continue editing or do we discard the saved work item and start again?

**Comment by Oanh-and-only-Oanh** [comment]
If the user click "start work" it should start with a fresh wizard. 

If they have drafts already exists, they should appear on their dashboard but they should start on a new wizard if they click on "start work".

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/59
