### ISSUE TITLE
App throws a white page when selecting 'FINAL DELIVERABLE FORMAT'on the branding step

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#121]
**Steps**
Go to Dashboard
Click on any draft
Proceed till branding step
select an option from 'FINAL DELIVERABLE FORMAT'on the branding step

Opens a white page

![image](https://user-images.githubusercontent.com/4592712/151737312-d897a2e9-4b73-4432-8642-8bb60dfb628c.png)

https://user-images.githubusercontent.com/4592712/151737236-5d29d9b3-42f2-4379-8580-295b558f076e.mp4

**Comment by sdgun** [comment]
@ThomasKranitsas Also throwing a white page when selecting "No, do not allow stock photos" option in "ALLOW STOCK PHOTOS?" on Branding step

**Comment by ThomasKranitsas** [comment]
this has been fixed, please check

**Comment by sandhiyakavi** [comment]
Verified in dev Env. Issue is resolved now.


https://user-images.githubusercontent.com/55895538/151786208-f7566e81-f77c-47b1-9e34-9137350cb40f.mp4
