### ISSUE TITLE
Only the user who created the work should be able to access the Work Details page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#124]
Only the user who created the work should be able to access the Work Details page

At present any logged in user can access the work details page using the URL
To reproduce the issue, login as any user and try accessing the below work. The work was created by user `tester1234`
https://platform.topcoder-dev.com/self-service/work-items/830d25b0-53c3-4536-9798-61a16fc03441?tab=summary

<img width="1440" alt="Screenshot 2022-01-31 at 10 57 58 AM" src="https://user-images.githubusercontent.com/58783823/151743390-a87c2f19-f9b0-454b-8657-5626bcbc03f9.png">

**Comment by Oanh-and-only-Oanh** [comment]
Outcome depends on if the solution is front-end or backend solution.
If the solution is done on the front-end, we need to implement a backend solution Post-MVP.

**Comment by ThomasKranitsas** [comment]
Fixed. Now, you will be redirected back to the main page if the work item is not yours

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-552

**Comment by sandhiyakavi** [comment]
verified in Dev Env. User is now redirected to their own Dashboard page.


https://user-images.githubusercontent.com/55895538/152281182-7d3988d4-c6b5-4ebe-a48e-a30b529e0c59.mp4
