### ISSUE TITLE
The number of days do not match the design on the 'Select Work Type' page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#126]
**Steps**
Go to https://platform.topcoder-dev.com/self-service/wizard
Check the Days after the price

App has 4-6 days
Design has 5-7 days

Design:
![image](https://user-images.githubusercontent.com/4592712/151752915-9eb0c420-59b2-4e9d-a788-83ccfe7d247a.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151752879-32ea37f2-e58f-48d7-83de-39b4b6f5c273.png)

**Comment by SathyaJayabal** [comment]
@sdgun  4-6 is correct based on current calculations
