### ISSUE TITLE
Some text/styles don't tally with the design

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#127]
**Issue 1**
Page: https://platform.topcoder-dev.com/self-service/basic-info

App: Give your project a descriptive title. This title is what the designers will see when looking for your work.
Design: Give your project a descriptive title. This is what the designers will see when looking for your work.

**Issue 2**
Page: https://platform.topcoder-dev.com/self-service/basic-info

In the NOT SEEING WHAT YOU NEED? section, the design shows the last sentence in blue, but the app doesn't. Also button not available in design

Design:
![image](https://user-images.githubusercontent.com/4592712/151755713-0e8254d8-7446-43ad-8113-0caba295c4f6.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151755757-bab6a6a4-0b0b-46db-aa96-8e96ea560d57.png)

**Issue 3**
Page: All steps

The step name is  bold in the design and not bold in app

Design:
![image](https://user-images.githubusercontent.com/4592712/151756052-3d5b4b6f-632d-41e5-bbff-fe3dcc82f87d.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151756109-59213736-6ed5-4419-9d37-6e7c10b05a1c.png)

**Issue 4**
Page: All steps

Latest design doesn't show label 'Price' before the price, but the app does

Design:
![image](https://user-images.githubusercontent.com/4592712/151756698-3f0d397c-e0d6-4db2-857e-32b43760b8af.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151756679-8a100f3b-e602-449f-a17a-bbcc0f1b258a.png)

**Issue 5**
Page: All steps

The field names should be bold

Design:
![image](https://user-images.githubusercontent.com/4592712/151756955-c4096509-fe38-4a95-ae6e-a7c40e083ab5.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151757019-a1383066-8379-4e1f-b8b3-67c966fd6a20.png)

**Issue 6**
Page: https://platform.topcoder-dev.com/self-service/page-details

Design:
![image](https://user-images.githubusercontent.com/4592712/151757501-950debfd-2bac-443e-86ac-7a69b3aba3ba.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151757533-44aa8443-0c57-4f13-8205-4a17b18dfb44.png)

**Issue 7**
Page: https://platform.topcoder-dev.com/self-service/page-details(EXAMPLE PAGE DESCRIPTION section)

The text after Main Body should come in a new line

Design:
![image](https://user-images.githubusercontent.com/4592712/151759860-ceab05a8-e8a0-480b-ba33-85f3612d8357.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151759897-75cb6f8f-1dca-4798-98c9-3855a3aec2cc.png)

**Issue 8**
Page: https://platform.topcoder-dev.com/self-service/branding

STYLE & THEME section, design shows everything in one paragraph but app has 2 paragraph 
Also the second paragraph font is different

Design:
![image](https://user-images.githubusercontent.com/4592712/151760175-1e81003c-6d96-4f63-8e45-aa2dd60977cf.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151760121-c1e9a0b7-395e-4eaa-8e83-eec3ee3fccce.png)

**Issue 9**
Page: https://platform.topcoder-dev.com/self-service/branding

"etc" missing in OTHER ASSETS (OPTIONAL) section

Design:
![image](https://user-images.githubusercontent.com/4592712/151760903-6c6e5c82-e848-48be-b985-9d9fda337ff9.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151760933-7ac7adb4-adea-40cf-a9ff-019b301b6691.png)

**Issue 10**
Page: https://platform.topcoder-dev.com/self-service/branding

Last section title different from design
Last section options deviate

Design:
![image](https://user-images.githubusercontent.com/4592712/151761271-c8a83f1c-9459-414b-abba-2da66dbe0a1d.png)

App:
![image](https://user-images.githubusercontent.com/4592712/151761317-d373d4e5-6aa8-4d39-9180-02f0d9682e8e.png)

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-564

**Comment by sdgun** [comment]
Verified in Dev, below is the status of issues, the not fixed one we will ignore based on the comment https://topcoder.atlassian.net/browse/PLAT-507?focusedCommentId=16931

Fixed
Issue 1, Issue 4, Issue 6, Issue 7, Issue 8, Issue 9, Issue 10

Not Fixed
Issue 2, Issue 3, Issue 5

**Comment by sdgun** [comment]
Verified in productin. Issue 1, Issue 4, Issue 6, Issue 7, Issue 8, Issue 9, Issue 10 are fixed.
