### ISSUE TITLE
Link in the terms popup is incorrect

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#129]
Link in the terms popup is incorrect
<img width="1440" alt="Screenshot 2022-01-31 at 5 32 36 PM" src="https://user-images.githubusercontent.com/58783823/151790674-e791fd58-1cd6-49df-996b-632ba25efd67.png">

expected: https://www.topcoder.com/policy/privacy-policy

**Comment by ThomasKranitsas** [comment]
@Oanh-and-only-Oanh do we want to link users to that page?

**Comment by SathyaJayabal** [comment]
The existing link goes to a page not found. i think its an older link maybe.

**Comment by Oanh-and-only-Oanh** [comment]
We will open a new tab if use clicks on that link from the pop up modal.

**Comment by SathyaJayabal** [comment]
verified on dev
<img width="1440" alt="Screenshot 2022-02-01 at 7 51 10 AM" src="https://user-images.githubusercontent.com/58783823/151904125-12d793a4-83a2-4bdc-8408-1f40621cf00e.png">
