### ISSUE TITLE
Navigating around the wizard should take you to top of page

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#13]
**Describe bug**
When user navigate throughout the wizard, they are not taken to the top of the page which requires the user to scroll up 

**Expected behavior**
Navigating around the wizard should take you to top of page

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/50
