### ISSUE TITLE
Messages tab: for a completed work, there is a link to the challenge 

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#131]
Messages tab: for a completed work, there is a link to the challenge. We should not have links leading out to other apps from the self service app.

<img width="1440" alt="Screenshot 2022-02-01 at 8 14 55 AM" src="https://user-images.githubusercontent.com/58783823/151905970-738f5c52-41b9-462a-883d-a36e497fba49.png">

**Comment by sdgun** [comment]
Verified in Dev. This issue is fixed.

![image](https://user-images.githubusercontent.com/4592712/152107100-3f316f59-0ebb-46fb-a361-84b7f67f9de8.png)
