### ISSUE TITLE
The price is incorrect when selecting pages randomly and throws a white page

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#132]
**Steps**
Start a new work or open an existing work
On the Basic info step, select page options randomly(select 1 page then 2 pages and next 5 pages) and observe the price(on top) and price shown under Device type(tablet/phone)

The prices are messed up and sporadically throws a white page while selecting page options

![image](https://user-images.githubusercontent.com/4592712/151911538-d3bc8afc-2813-450e-ab28-80dcff66a9de.png)

https://user-images.githubusercontent.com/4592712/151911905-99d5bb71-2789-4373-9f70-9ff3fbaad725.mp4

https://user-images.githubusercontent.com/4592712/151912168-73b45f36-9daf-46d0-8a5c-f2179c0b0fff.mp4

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , this happens when u select 5 pages plus all devices.

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-551

**Comment by sdgun** [comment]
Verified in dev, this issue is fixed.
