### ISSUE TITLE
Rating for completed work keeps changing randomly

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#135]
Rating for completed work keeps changing randomly
<img width="1440" alt="Screenshot 2022-02-01 at 11 08 15 AM" src="https://user-images.githubusercontent.com/58783823/151918209-514c70c0-aa29-4742-ae2d-1a39ffd60063.png">

https://user-images.githubusercontent.com/58783823/151918219-004b2979-0eed-4b80-8a16-b894b63134a0.mov

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-550

**Comment by sdgun** [comment]
@ThomasKranitsas Verified by creating a new SS challenge, after completing the survey the ratings are not displayed at all. Tried refreshing and re-logging too.

Ex challenge -  https://platform.topcoder-dev.com/self-service/work-items/2093bf15-c34a-4cc7-9100-1ffd6a079d86?tab=summary (user - Tcconadmin)

**Comment by sdgun** [comment]
Verified in Dev, still we cannot see the ratings.


https://user-images.githubusercontent.com/4592712/156697949-3b1f607b-9709-4c27-9b69-88a92a003f35.mp4

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.


https://user-images.githubusercontent.com/4592712/156972077-629fcb4c-fa28-48d9-a6a8-a3f8cbd23b27.mp4
