### ISSUE TITLE
Entered information on Step2 and 3 of work item are not preserved once the user logs in

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#136]
Steps
Go to https://platform.topcoder-dev.com/self-service/(do notlog in)
Create new work item, fill in required information and log in when prompted

Entered information on Step2 and 3 of work item are not preserved once the user logs in

https://user-images.githubusercontent.com/4592712/151919476-c503326d-a8ab-4221-bc9b-350572b56038.mp4

**Comment by SathyaJayabal** [comment]
For me, after logging in it took the user to the empty Page details step (step 3).
Expected: It should take the user to the Branding Page (step 4)

**Comment by ThomasKranitsas** [comment]
Can't reproduce
