### ISSUE TITLE
Every Wizard step should include Website Design and Price at the top 

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#14]
Every Wizard step (including Review) should include Website Design and Price at the top (see wireframes for format)

**Comment by trevorgerring** [comment]
![Screen Shot 2022-01-07 at 9 10 40 PM](https://user-images.githubusercontent.com/21342409/148630972-4f44d598-03d3-4e1a-8b90-2536b728bbe1.png)

This area should appear on all steps. Designs are updated in Figma

**Comment by ThomasKranitsas** [comment]
Fixed https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/51
