### ISSUE TITLE
Received Work has begun notification mail twice

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-self-service-app#142]
Description:

"The Work has begun" notification mail is received twice. One after the copilot Approves the challenge and the other when they Launches the challenge.

**Comment by Oanh-and-only-Oanh** [comment]
**Expected behavior:**
There should be 2 customer emails:
1) "Work was submitted"
2) "Work has begun"

**Comment by sandhiyakavi** [comment]
The issue still exists, Customer receives two "Work has begun" emails (one for Approve and another one for Launch)

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-560

**Comment by sandhiyakavi** [comment]
Verified the issue. Only one " Work has begun" mail is received after the copilot Launches the challenge.

![image](https://user-images.githubusercontent.com/55895538/152279316-3dfe9c97-f5bc-4a96-939b-95fa74fa2e6b.png)
