### ISSUE TITLE
Content added from SS wizard missing in challenge

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#145]
Content added from SS wizard missing in challenge
Related issues in Work Manager
https://github.com/topcoder-platform/work-manager/issues/1289
https://github.com/topcoder-platform/work-manager/issues/1288

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-547

**Comment by Oanh-and-only-Oanh** [comment]
@ThomasKranitsas couldn't reproduce the issue. @SathyaJayabal can you re-test please?

**Comment by Oanh-and-only-Oanh** [comment]
@SathyaJayabal, can you test with other kinds of data/fields and see if you can be more specific with steps to reproduce?

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh , are you able to see all details that you entered in the challenge spec in WM ?

Steps to reproduce:
1. create a WR using the wizard. Please fill in all fields including optional ones.
2. submit the WR
3. Go to Work Manager.
4. Find and Open the project under Self service opportunities -> waiting for approval
5. check the challenge spec

You should see all details that you entered in the wizard here.

**Comment by Oanh-and-only-Oanh** [comment]
These are the inputs in the wizard.
![image](https://user-images.githubusercontent.com/47536078/152429051-c7a99c08-991c-473a-9da6-899c34263a62.png)

Compare that to the challenge spec in the Work Manager. 
![image](https://user-images.githubusercontent.com/47536078/152429214-3526adb7-890f-4d92-9f40-c886e0a242d0.png)
![image](https://user-images.githubusercontent.com/47536078/152429441-4f15c7a8-3a7c-42fc-9948-f0e74c943ab3.png)
![image](https://user-images.githubusercontent.com/47536078/152429539-34ebe8c4-1545-4d76-ab2f-373d767845cf.png)

1. number of screen is incorrect
2. Type of devices is incorrect
3. Screen details is missing
4. Inspiration input is missing
5. Custom color input is missing
6. Custom font input is missing
7. custom assets input is missing
8. "what to avoid" input is misisng

**Comment by Oanh-and-only-Oanh** [comment]
verified in PROD
