### ISSUE TITLE
Mark as Done button is also displayed under the Messages tab

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-self-service-app#147]
Description:

Mark as Done button is also displayed under the Messages tab.

https://user-images.githubusercontent.com/55895538/152136115-2c6a9731-507f-4824-82cf-89aee3c3a752.mp4

**Comment by jmgasper** [comment]
@ThomasKranitsas - I don't think this is coming from the embedded forum.  If it is, let me know so we can investigate, thanks.

**Comment by Oanh-and-only-Oanh** [comment]
The Done button should be on all tabs. This is as designed. closing ticket.
