### ISSUE TITLE
User must be logged in before Branding page

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#15]
**Describe bug:**
Currently, if user is not logged in when they are completing the wizard, login/signup is trigged after the review page before payment page.

**Expected behavior:**
If user is not logged in when they are completing the wizard, login/signup should be trigged before the branding page.

**Comment by ThomasKranitsas** [comment]
Design https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=1725%3A4438

Note: this page will not be counted as a "Step". it's just a warning that the user must login to move to the next step.

**Comment by ThomasKranitsas** [comment]
Login URL: https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fplatform.topcoder-dev.com%2Fself-service%2Fwizard&regSource=selfService
SignUp URL: https://accounts-auth0.topcoder-dev.com/?retUrl=https%3A%2F%2Fplatform.topcoder-dev.com%2Fself-service%2Fwizard&regSource=selfService&mode=signUp

**Comment by ThomasKranitsas** [comment]
PR https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/68
