### ISSUE TITLE
Complete authentication flow is not working

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#150]
**Steps**
Go to https://platform.topcoder-dev.com/self-service/
start new work
Fill in data till payment step
Enter test card number 4000 0025 0000 3155(Payment requires authentication flow)
complete authentication

Expected: Payment should be authorized

Actual: Card is declined

https://user-images.githubusercontent.com/4592712/152142818-102f7be1-e506-4779-9c89-f0fee6993be4.mp4

**Comment by Oanh-and-only-Oanh** [comment]
@sdgun @SathyaJayabal @ThomasKranitsas, is this a dev environment issue or a bug we'd see in prod as well?

**Comment by Oanh-and-only-Oanh** [comment]
https://topcoder.atlassian.net/browse/PLAT-545

**Comment by sdgun** [comment]
Verified, this issue is fixed.
