### ISSUE TITLE
Work Id is not displayed in the Dashboard page

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-self-service-app#151]
Description:

Work Id is not displayed in the Dashboard page (as per design)

![image](https://user-images.githubusercontent.com/55895538/152147019-67663ebd-f2f1-45c9-b541-321c5b28a2ad.png)

Design:

![image](https://user-images.githubusercontent.com/55895538/152147087-96bd2e7c-cfdc-470a-acd3-03396ae97ede.png)

**Comment by Oanh-and-only-Oanh** [comment]
do removed ID in the design. closing issue.
