### ISSUE TITLE
The payments is declined with an error

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#163]
**Steps**
Go to SS app and start a new work
Proceed till payment page
Enter valid card details and pay

The URL shows https://api.topcoder-dev.com/v5/challenges/undefined and the payment is declined

![image](https://user-images.githubusercontent.com/4592712/152726473-b216be9a-84c8-476c-ab42-2b608af30a9c.png)

![image](https://user-images.githubusercontent.com/4592712/152726494-06ca80c2-30a4-4233-b64b-aac083d51aba.png)

**Comment by ThomasKranitsas** [comment]
<img width="1587" alt="Screenshot 2022-02-07 at 1 42 04 PM" src="https://user-images.githubusercontent.com/4612921/152781839-299a076b-24dd-4cb8-ad59-8d93872b5c8f.png">

I'm not able to reproduce the issue

**Comment by sdgun** [comment]
Verified in Dev, this issue cannot be reproduced anymore.
