### ISSUE TITLE
Start date for SS challenges is set 3 days late

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-self-service-app#171]
Description:

The Start date for Self service challenges is set late by 3 days. Also the Screening date is too late but it is autocorrected after opening the Registration phase.

<img width="960" alt="startdate_late" src="https://user-images.githubusercontent.com/55895538/153544212-e0a2b10b-fe4b-4997-9bdc-b9716b5d374b.png">

**Comment by ThomasKranitsas** [comment]
This is expected behaviour. The start date is 1 business day after the current date so If you submit it on Friday, it's expected to be launched on Monday (3 days)
