### ISSUE TITLE
Work Started Email must be sent only when registration phase opens

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#181]
Work Started Email must be sent only when registration phase opens. At present it is sent after the Customer Assistant approves the work. 
<img width="605" alt="Screenshot 2022-02-18 at 7 15 32 PM" src="https://user-images.githubusercontent.com/58783823/154694210-14fc7e08-c20f-4c3a-9577-2ba96a5ca1d2.png">

**Comment by ThomasKranitsas** [comment]
Expected behaviour

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , the mail says that users can register and start work. Is this not misleading especially with the one business day delay in launching the challenge?
