### ISSUE TITLE
New Message Notification is not displayed on dashboard and message tab

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#182]
New Message Notification is not displayed on dashboard and message tab. This was working before.
<img width="1173" alt="Screenshot 2022-02-18 at 7 17 03 PM" src="https://user-images.githubusercontent.com/58783823/154694508-46a03212-5216-41cf-bf5b-e67078dec6bd.png">
<img width="1440" alt="Screenshot 2022-02-18 at 7 17 20 PM" src="https://user-images.githubusercontent.com/58783823/154694515-746cba4f-563c-472c-b655-7776d4386b51.png">

**Comment by ThomasKranitsas** [comment]
@jmgasper can you please look into this?

**Comment by jmgasper** [comment]
@SathyaJayabal - Can you include test account details please?

**Comment by SathyaJayabal** [comment]
@jmgasper , sent on  slack

**Comment by jmgasper** [comment]
Just to clarify - I don't think this is a problem.  I tested and things worked appropriately.  In the test details, I noted that user `jcori` was used as the client manager *and* the test registered user.  In that case, we will **NOT** show the notification for a new message, if the user posting the message is the same as the client manager.  The counter will only show for new messages from someone *other* than the client manager

**Comment by SathyaJayabal** [comment]
@jmgasper , I did use another user to post the message. Looks like it is working for only user `jcori`. Can you try with this one pls.
https://platform.topcoder-dev.com/self-service/work-items/5a9ecdba-450d-483c-8081-a583117d0c0c?tab=summary
client user (tester1234) 

Please register and pots for this challenge
https://www.topcoder-dev.com/challenges/5a9ecdba-450d-483c-8081-a583117d0c0c?tab=registrants.
Creds shared on slack

**Comment by SathyaJayabal** [comment]
Closing this as the issue is not reproducible
