### ISSUE TITLE
Step 3: Basic info page

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#19]
1. Under Device Types:
- Computer is always selected 
- Table and Phone are both toggles. User can select neither, one, or both

2. Tooltip (beside price/$499 on this screen) should present a text field
UX will decide on modal or drop-down format

3. User data should be preserved when refreshing or going back (get it from cookies)

**Comment by trevorgerring** [comment]
The tooltip component should be used whenever we have the (?) icon. 
![Screen Shot 2022-01-07 at 9 22 20 PM](https://user-images.githubusercontent.com/21342409/148631230-af0dc40f-18cf-4176-ab11-470a5e9c9726.png)

Component is designed in Figma here: https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=487%3A3948

**Comment by code2nguyen** [comment]
Hi, Do we have Modal Mode Design for (?) icon. Or we support only DropDown Format ?

**Comment by code2nguyen** [comment]
I see, about this spec `UX will decide on modal or drop-down format`.... So for drop-down format, I guess it like the design when user move hover ? icon.

And about Modal format.... this is my question.

**Comment by trevorgerring** [comment]
@code2nguyen You can ignore that comment about the Modal or dropdown. The ? icon should be what's seen in the design that @ThomasKranitsas linked to. It should show the tooltip on hover of the ? No modal is needed for the tooltip.

**Comment by code2nguyen** [comment]
hi, I can not create branch/PR....should I fork it then create a PR from my fork ?

**Comment by ThomasKranitsas** [comment]
@code2nguyen yes, please

**Comment by code2nguyen** [comment]
ok, Here is the PR: https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/73
