### ISSUE TITLE
Step 5: Page details

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#21]
1. The number of pages are pre-populated (in Page Details) should match # of pages selected in step 1 (Basic info). When "add page" is selected, the price change should reflect the # of devices as well 

2. `See an example page description`
Should not link out
Will be expandable and collapsible block

**Comment by trevorgerring** [comment]
"Example page description" expandable box design: https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=172%3A5754

Expanded: https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=487%3A4052

**Comment by SathyaJayabal** [comment]
@Oanh-and-only-Oanh, how are prices between and number of pages and prices related. For example if the user selects 5 pages vs 1 page , will the price for adding mobile and tablet also change ? And vice versa , if the user has added both mobile and tablet versions, does the price per page change ?

Also in the Basic Info page, we have only options to add up to 5 pages. Should the last option be worded a bit more openly like "More than 5 pages (from $000 Onwards) ?
