### ISSUE TITLE
Step 6: Branding

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#22]
1.`Add another Website` button doesn’t work

2. Color selection should allow up to 3 colors
    - No default selected
    - Move "Any colors" to first option
    - Once 3 are selected, user must deselect one to add another. Minimum you can select is 0 (because user would input text field)
    - Make free-text field persistent
    - If no color boxes are selected, free text field becomes a mandatory field to go to next step

3. Add ‘No preference’ option for Fonts
    - User should only be able to select 1 

4. Upload Fonts
- Replace the upload button with the inputs to provide a link to a downloadable file as per the following design https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=1725%3A4077

5. Other Assets
- Replace the upload button with the inputs to provide a link to a downloadable file as per the following design https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=1725%3A4077

6. Learn more about our stock photo policy
- link needs to be updated to show the modal from the following design https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=1725%3A5204
- Get the modal content from https://www.topcoder.com/thrive/articles/stock-artwork-font-and-icon-policies

7. Change "Allow stock photos?" options to be radio buttons instead of drop down
- default to Yes option

8. Final deliverable source files
- Alphabetize with “Any” on top and “Other” on the bottom
- other should be free text

**Comment by trevorgerring** [comment]
Updated design file here: https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=172%3A6081

**Comment by ThomasKranitsas** [comment]
PR https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/75
