### ISSUE TITLE
Step 7: Review

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#23]
1. Add new sections called Project Type & Price
2. Show all fields from all wizard steps
  - If no data, show ‘(no input)’
3. There should just be one Edit link, beside page header (Review)
4. Default to full expanded view
5. The attestation should convey `Details above accurately describe what I want to build. If the above requirements are satisfied I’ll be happy. I understand I can’t change these requirements or the scope of the effort after this step.`
6. Attestation tex should be moved to the right before the “next” button

Design: https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=1725%3A4453

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/65
