### ISSUE TITLE
Customer manage work item (summary)

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/micro-frontends-self-service-app#26]
After the user has logged in, from the dashboard page, clicking on any work item row should take him to the `Summary` page of the work item details page (https://platform.topcoder-dev.com/self-service/work-items/:challengeId?tab=summary)

### Design
![Work Details - Summary V2](https://user-images.githubusercontent.com/4612921/149237205-6e8e00f2-24c0-497b-8d95-e26a6ddbc987.png)

![Work Details - Summary-sent to solutions expert](https://user-images.githubusercontent.com/4612921/149237218-ec324859-1ca0-4de1-b917-f0b10a8df811.png)

### Terminology / logic behind each term
- `Status`: same logic as the status from the dashboard
- `Next action`: determined based on the current active phase of the challenge. If the challenge has `status=New` the next action will be `Submit work`, else if it is `Draft` or `Active` it will be `Accept` else hide the next action
- `Work submitted`: The challenge creation date
- `Work started`: The registration phase start date
- `Work finished`: The submission phase end date
- `Downloads ready`: The appeals response phase end date
- `Mark as done`: If the challenge status is `Completed`, the challenge update date
- `Send to solutions`: If the status is `Canceled`, the challenge update date
- `Work ID`: the challenge ID

**Comment by painterner** [comment]
> Status: same logic as the status from the dashboard

Where to find the specification

**Comment by painterner** [comment]
Are `Downloads ready` and `Mark as done` clickable ? i.e.
Click `Downloads ready` should redirect to `SOLUTIONS` tab.
Click `Mark as done` should update challenge end date.
right ?

**Comment by morehappiness** [comment]
please ask question in forum. Thanks
