### ISSUE TITLE
Customer manage work item (solutions)

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/micro-frontends-self-service-app#27]
This is the page where the challenge submissions can be found and downloaded.

This is what the user should see if the review phase is not yet completed:
![Work item - solutions-empty](https://user-images.githubusercontent.com/4612921/149238333-3e8a4cfa-24f7-4db9-ae09-2867def628fc.png)

And this is what he should see after the end of the review phase:
![work item - solutions](https://user-images.githubusercontent.com/4612921/149238354-04ab53b3-42d3-4c7f-8705-768a2ba8a05f.png)

### Notes
- Submissions should be ranked based on their score.
- Omit the `download all submissions` link
- Omit the `Need help?` link

**Comment by painterner** [comment]
1.
> And this is what he should see after the end of the review phase

==> Shouldn't it be after appeal response phase ?

2.
Should hide `download all submissions` and `Need help?` links  or show as dummy links ?

**Comment by morehappiness** [comment]
please ask question in forum. Thanks
