### ISSUE TITLE
Customer manage work item (final survey)

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/micro-frontends-self-service-app#28]
Inside the work item page (any tab), if the challenge status is `Completed` and IF the challenge.metadata does not include an entry for the `customerFeedback`, show the footer with the `MARK AS DONE` button.
![work item - solutions](https://user-images.githubusercontent.com/4612921/149238943-beab2d7d-eef9-46d4-8a66-ce9ff0f1d2d8.png)

Clicking that button should show the following

![Survey modal](https://user-images.githubusercontent.com/4612921/149238969-83a78e78-5e5b-474f-b3b2-3a20da0874b6.png)

![work item - final survey](https://user-images.githubusercontent.com/4612921/149238974-1103ba31-718b-4b3b-9883-47d5241c333b.png)

The content of the review form should be saved in the challenge object inside the metadata with the `name` `customerFeedback`

**Comment by painterner** [comment]
> The content of the review form should be saved in the challenge object inside the metadata with the `name` `customerFeedback`

==> with the name  `customerFeedback` ?

**Comment by morehappiness** [comment]
please ask question in forum. Thanks
