### ISSUE TITLE
Forums not displaying

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-self-service-app#35]
@nursoltan-s - I'm seeing an odd issue - the forums have stopped showing up entirely in the `Messaging` tab.  I see no indication of any errors with Vanilla, and the Vanilla settings seem OK and the embed works at https://platform.topcoder-dev.com/forums.

Can you debug a bit please and let me know what you see?  There was a large check-in to the self-service app earlier today, but it doesn't appear to touch anything related to the work items.

**Comment by nursoltan-s** [comment]
Can you please look at this PR:
https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/36

After latest branch merge, services/challenge.js getChallenges method modified and broken work items page.

**Comment by ThomasKranitsas** [comment]
@jmgasper what's the status here?

**Comment by jmgasper** [comment]
@ThomasKranitsas - This is done.  Closing now.  Sorry, was tracking this in a separate repo.
