### ISSUE TITLE
Frame sizing for Vanilla discussion

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-self-service-app#41]
@nursoltan-s - I'm seeing that the frame isn't fully showing.  This means that the bottom of the Vanilla frame is slightly cut off - can we fix that please?
<img width="1430" alt="Screen_Shot_2022-01-19_at_7_57_08_am" src="https://user-images.githubusercontent.com/21790/150017485-6fb24118-4de9-4706-9f47-f1643c6c9b82.png">

**Comment by nursoltan-s** [comment]
@jmgasper 
Hi,Please check these 2 MRs:https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/43
https://github.com/topcoder-platform/micro-frontends-navbar-app/pull/67

For navbar repo, I found a bug from yesterday's merged code. And I fixed it. Can you please check it?

**Comment by ThomasKranitsas** [comment]
@jmgasper update please?

**Comment by jmgasper** [comment]
@ThomasKranitsas - This is done.  Closing now.  Sorry, was tracking this in a separate repo.
