### ISSUE TITLE
Notification count showing incorrectly

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-self-service-app#53]
@nursoltan-s:

* User `TCConnCopilot` / `Appirio123`
* URL:  https://platform.topcoder-dev.com/self-service/work-items/34630a3b-55ce-40a6-b1c2-2f049e73c66b?tab=messaging

### Problem

The user has no unread messages (count==0), but the `0` is showing at the end of the `MESSAGES` text.  Can we hide the `0` if there are no unread messages please?

### Screenshot
<img width="662" alt="Screen_Shot_2022-01-21_at_11_47_05_am" src="https://user-images.githubusercontent.com/21790/150445489-b95cf304-d2b2-4ff6-97d7-e361fc66fbe0.png">

**Comment by nursoltan-s** [comment]
@jmgasper Hi.sure let me fiz that real quick

**Comment by nursoltan-s** [comment]
https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/54

**Comment by jmgasper** [comment]
@nursoltan-s - Looks good, thanks!
