### ISSUE TITLE
Missing "Discussions" array on challenge object

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-self-service-app#64]
### Bug

When the self-service app creates a new challenge, the template used doesn't have the `discussions` array, which means that the challenge-forum-processor ignores the challenge and doesn't create a Vanilla forum for it

### Fix

We should implement this similar to Work Manager, with the discussion object being part of the challenge object.

https://github.com/topcoder-platform/work-manager/blob/3e3f19a8999d84aa5185776eb11c36c48796e2d3/src/components/ChallengeEditor/index.js#L929

```
  "discussions": [
    {
      "name": "Justin copilot test Discussion",
      "type": "challenge",
      "provider": "vanilla",
      "id": "4017b648-bb81-45c2-b686-d0e35ecc1cff"
    }
  ],
```

**Comment by ThomasKranitsas** [comment]
When activating a work item, append the below object to the challenge body:
```
 "discussions": [
    {
      "name": <workItem.name>,
      "type": "challenge",
      "provider": "vanilla"
    }
  ],
```

**Comment by ThomasKranitsas** [comment]
Fixed https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/66

**Comment by jmgasper** [comment]
@ThomasKranitsas - This isn't quite right - we need that discussions object when the challenge is *created*, not when it's updated.  Currently, the challenge forum creation is tied to the `challenge.notification.create` Kafka message, not the update one, so the forum still isn't getting created because the array doesn't exist at creation.  I'm discussing with @Oanh-and-only-Oanh about potential workarounds, but I'm going to open this back up so we can track it still.

**Comment by jmgasper** [comment]
Created a fix here to allow for support for the existing flow, for testing:

https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/72

**Comment by ThomasKranitsas** [comment]
@jmgasper have you tested this? Can we close this ticket?

**Comment by jmgasper** [comment]
@ThomasKranitsas - Yeah, my fix worked, but please just review it to make sure it makes sense with the rest of the flow of the self-service stuff.

**Comment by ThomasKranitsas** [comment]
I updated the code so it updates the name of the challenge forum on activation
