### ISSUE TITLE
Don't see "client manager" role

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-self-service-app#71]
@ThomasKranitsas / @Oanh-and-only-Oanh - I created a self-service challenge using `jgasperMobile12`, one of my test accounts.

I'm seeing in OR that that account isn't registered as `Client Manager`, which is important because we've built a bunch of stuff in to the Vanilla tied specifically to that role.  Is that a problem with how the challenge was launched, or something else?

* OR:  https://software.topcoder-dev.com/review/actions/ViewProjectDetails?pid=30060647
* WM: https://challenges.topcoder-dev.com/projects/19744/challenges/35e65e8d-4797-488e-8bd2-4632977449d0/view
* SS: https://platform.topcoder-dev.com/self-service/work-items/35e65e8d-4797-488e-8bd2-4632977449d0

<img width="594" alt="Screen Shot 2022-01-25 at 9 33 47 am" src="https://user-images.githubusercontent.com/21790/150876288-416f0d1b-24f4-4f93-bf80-7557345cb957.png">

**Comment by jmgasper** [comment]
@ThomasKranitsas - Created a temp MR in the challenge API, just for testing:

https://github.com/topcoder-platform/challenge-api/pull/450

**Comment by ThomasKranitsas** [comment]
@jmgasper can we close this one? I checked the code and it looks ok
