### ISSUE TITLE
Hide "messages" tab on the dashboard until the challenge is active

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/micro-frontends-self-service-app#76]
@nursoltan-s - One change we'd like to make is to hide the `Messages` tab on the dashboard until the challenge transitions to the `Active` state:

<img width="1022" alt="Screen_Shot_2022-01-26_at_11_40_06_am" src="https://user-images.githubusercontent.com/21790/151083457-c2f0aae5-7395-4d5e-a25e-a980e7db3d5d.png">

**Comment by nursoltan-s** [comment]
PR: https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/85
