### ISSUE TITLE
"Select Work" page UX updates

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/micro-frontends-self-service-app#77]
1. Back button returns to parent page (wherever user came from)
2. Update the page based on the updated design https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=1779%3A4204

**Comment by Oanh-and-only-Oanh** [comment]
closing ticket
