### ISSUE TITLE
Payment page

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/micro-frontends-self-service-app#78]
Update the payments page based on the latest design from https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=1725%3A5047

Capture all additional information about the credit card and the customer and pass those into Stripe. Refer to the Stripe documentation for the exact details for each field https://stripe.com/docs/stripe-js/react

**Comment by doctorhilarius** [comment]
SEE PR https://github.com/doctorhilarius/micro-frontends-self-service-app/pull/1/files#diff-3fd1e8460afdb132a1a196172c38fb58da86abdbfab41ca0205d18762005a0b3R38
