### ISSUE TITLE
The Profile settings page has placeholder text instead of actual content

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-self-service-app#79]
Description:

The Profile settings page has placeholder text instead of actual content.

![image](https://user-images.githubusercontent.com/55895538/151107735-66a5f06f-826f-4092-8cd0-fe4b88370036.png)

**Comment by Oanh-and-only-Oanh** [comment]
closing. already in jira

**Comment by SathyaJayabal** [comment]
reopening to track by qa members

**Comment by SathyaJayabal** [comment]
placeholder text removed
<img width="1440" alt="Screenshot 2022-02-01 at 7 50 13 AM" src="https://user-images.githubusercontent.com/58783823/151904045-4adb6716-b3a4-4456-a141-e80d6ec9a5b0.png">
