### ISSUE TITLE
Home Page (Not logged in) should be first page

### ISSUE THREAD

**Issue by Oanh-and-only-Oanh** [topcoder-platform/micro-frontends-self-service-app#8]
If the user is not logged in, show the home page as the first screen before work type selection.

When you click Login, user should be taken to Customer Login page
When you click Sign up, user should be taken to Customer Registration page

design:  https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=168%3A6206

**Comment by trevorgerring** [comment]
@ThomasKranitsas I will have an update to this page by EOD. Will share the update once ready. FYI @Oanh-and-only-Oanh

**Comment by trevorgerring** [comment]
@ThomasKranitsas The homepage design has been updated. The Lorem ipsum may change to a bulleted list once we get copy back, but the overall layout shouldn't change.

New Homepage Design: https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=815%3A3798

**Comment by ThomasKranitsas** [comment]
Clicking SignUp should take the user to https://accounts-auth0.topcoder.com/?retUrl=https://platform.topcoder.com/self-service&regSource=tcBusiness&mode=signUp and clicking login should take the user to https://accounts-auth0.topcoder.com/?retUrl=https://platform.topcoder.com/self-service&regSource=tcBusiness&mode=login

The `retUrl` is the URL of the self service app.

**Comment by ThomasKranitsas** [comment]
Move the MyWork component to the `/self-service/dashboard` route and the Home to the landing page (`/self-service`)

**Comment by ThomasKranitsas** [comment]
fixed https://github.com/topcoder-platform/micro-frontends-self-service-app/pull/62
