### ISSUE TITLE
The step numbers in the create work wizard do not tally with the step numbering in the design

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#80]
**Steps**
According to the design/user story, the 'Select work type' should be the step 1, but in the implemented app, "BASIC INFO" is the Step 1

App:
![image](https://user-images.githubusercontent.com/4592712/151114616-30ed72aa-61fa-46d0-95aa-53185d743757.png)

Design:
![image](https://user-images.githubusercontent.com/4592712/151114815-4c14e99c-db85-4a71-8a08-1448f6474ec2.png)

**Comment by ThomasKranitsas** [comment]
Please refer to https://www.figma.com/file/61RVR37D1ifWPeeNdLH393/MVP-Work-Request-Handoff-(Ray's-File)?node-id=1725%3A3748

This is as expected
