### ISSUE TITLE
The price on the Basic info page is not adjusted based on the selected Device type

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#81]
**Steps**
1. Go to https://platform.topcoder-dev.com/self-service/basic-info
2. Select Tablet/phone from Device types and observe the price value on top of the page

The price on the Basic info page is not adjusted based on the selected Device type

![image](https://user-images.githubusercontent.com/4592712/151117309-d00caab5-5753-48cd-9eef-e83aa52cf23d.png)

**Comment by Oanh-and-only-Oanh** [comment]
closing. we have a jira ticket opened already.
