### ISSUE TITLE
When click on Review step from the progress indicator option, the payment step is checked

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/micro-frontends-self-service-app#82]
**Steps**
Go to https://platform.topcoder-dev.com/self-service/basic-info
Click on three dots near progress indicator
Keep selecting the steps untill review

When on review step, the payment step shouldn't be checked. But it gets selected now

![image](https://user-images.githubusercontent.com/4592712/151125108-ed7d9814-f2bf-43f9-ab81-0f98969fdc79.png)

**Comment by ThomasKranitsas** [comment]
@sdgun please verify the fix on dev

**Comment by sdgun** [comment]
@ThomasKranitsas This issue is fixed

**Comment by Oanh-and-only-Oanh** [comment]
closing ticket because it's fixed
