### ISSUE TITLE
Irrelevant notifications are getting displayed for the customer user.

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/micro-frontends-self-service-app#88]
Description:

The notifications that are not related to the Customer is displayed under the Bell icon. Also the customer is taken outside the self service app on clicking the View All notifications button.

![image](https://user-images.githubusercontent.com/55895538/151153873-13564bd0-19e6-45e8-ab56-ec4d8e7d1262.png)

https://user-images.githubusercontent.com/55895538/151153891-46a714fe-a017-4b0c-ada3-8382585a8f7a.mp4

**Comment by ThomasKranitsas** [comment]
The notifications will be removed for the self-service app
