### ISSUE TITLE
Basic Info: Page must be Pages when there is more than 1 page

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#95]
Basic Info: Page must be Pages when there is more than 1 page
<img width="940" alt="Screenshot 2022-01-28 at 9 27 38 AM" src="https://user-images.githubusercontent.com/58783823/151484888-391cd52e-191a-49c3-b4d3-c500f5e96d57.png">

**Comment by ThomasKranitsas** [comment]
@SathyaJayabal this is part of the fix that was recently deployed. Please check again.

Also, we removed the $$ amount from the title of each option

**Comment by sdgun** [comment]
This issue is fixed in Dev.

![image](https://user-images.githubusercontent.com/4592712/151738159-72d70a36-dfde-43ab-a34b-834bedd4161e.png)
