### ISSUE TITLE
Branding page : Font section options alignment issue

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#96]
Branding page : Font section options alignment issue. The options go out of the border
<img width="1428" alt="Screenshot 2022-01-28 at 11 04 08 AM" src="https://user-images.githubusercontent.com/58783823/151493834-6c91aaad-d158-4b0d-ab5c-82ee688332b2.png">

**Comment by Oanh-and-only-Oanh** [comment]
Not an issue. closing ticket.
