### ISSUE TITLE
Branding Page: Unable to enter text in the "How to Use Your Fonts (optional)" field

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#97]
Branding: Unable to enter text in the "How to Use Your Fonts (optional)" field
<img width="1340" alt="Screenshot 2022-01-28 at 11 15 52 AM" src="https://user-images.githubusercontent.com/58783823/151494040-fc88122e-f8aa-4206-bcc4-a3c5a1a2b710.png">

**Comment by sdgun** [comment]
This issue is fixed in Dev.

![image](https://user-images.githubusercontent.com/4592712/151738003-b43d7ea3-4711-43d5-88f8-c23920a42a0d.png)
