### ISSUE TITLE
Review Page: Minor UI issues

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#98]
1. Basic Info: Device Types

- `Computer` is displayed twice

- There must a space between the device types
<img width="1335" alt="Screenshot 2022-01-28 at 11 18 17 AM" src="https://user-images.githubusercontent.com/58783823/151494376-76a0cd88-b868-4c01-b876-846d30a82189.png">

2. Branding Color Option
- There must a space between the color options
<img width="585" alt="Screenshot 2022-01-28 at 11 41 10 AM" src="https://user-images.githubusercontent.com/58783823/151496509-83c9ab0c-c28c-48cb-b2fe-c62fa0c53dbc.png">

3. Branding: There is  an  extra "h" on the bottom of this section
<img width="702" alt="Screenshot 2022-01-28 at 11 42 15 AM" src="https://user-images.githubusercontent.com/58783823/151496647-fe0d8266-1a97-480c-a433-c1b567dcb9e5.png">

4. Branding :Type in the word deliverable
<img width="444" alt="Screenshot 2022-01-28 at 11 49 00 AM" src="https://user-images.githubusercontent.com/58783823/151497523-c7116ce3-8004-40e3-808d-7261595bcdc2.png">

**Comment by Oanh-and-only-Oanh** [comment]
closing because there's a jira ticket for these UI issues already

**Comment by SathyaJayabal** [comment]
Reopening to keep track as not all of us have access to JIRA

**Comment by SathyaJayabal** [comment]
@ThomasKranitsas , point 4 is still not fixed (Branding :Type in the word `deliverable`)
<img width="495" alt="Screenshot 2022-02-01 at 8 39 52 AM" src="https://user-images.githubusercontent.com/58783823/151907692-7880fdff-1888-44be-9300-3fa3307acf43.png">

**Comment by sdgun** [comment]
Verified in Dev, this issue is fixed.

**Comment by SathyaJayabal** [comment]
fixed
<img width="1440" alt="Screenshot 2022-02-02 at 9 53 37 PM" src="https://user-images.githubusercontent.com/58783823/152194475-9edc916e-4a7c-4735-917e-063853a5db79.png">
