### ISSUE TITLE
Payment Page does not reflect the correct amount

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/micro-frontends-self-service-app#99]
Payment Page does not reflect the correct amount.
Example:
<img width="1359" alt="Screenshot 2022-01-28 at 11 46 34 AM" src="https://user-images.githubusercontent.com/58783823/151497261-32371e3c-cdc1-48f3-809c-e29dd3d9a830.png">

<img width="1378" alt="Screenshot 2022-01-28 at 11 46 12 AM" src="https://user-images.githubusercontent.com/58783823/151497250-120338ac-c011-4c24-a9fa-20b8712ed417.png">

**Comment by ThomasKranitsas** [comment]
@SathyaJayabal this is part of the fix that was recently deployed. Please check again

**Comment by sdgun** [comment]
Verified in Dev, issue is fixed.

![image](https://user-images.githubusercontent.com/4592712/151914183-9d1c2e8b-8cc9-489c-b498-0f669d0e84b6.png)
